//! Raw libopus bindings generated by `tools/ndk-bindgen` from `vendor/opus/include/opus.h`.
//! Regenerate: `just bindgen`. libopus itself is built statically by `build.rs`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[cfg(target_arch = "arm")]
include!("ffi_arm.rs");
#[cfg(target_arch = "aarch64")]
include!("ffi_aarch64.rs");
#[cfg(target_arch = "x86")]
include!("ffi_i686.rs");
#[cfg(target_arch = "x86_64")]
include!("ffi_x86_64.rs");
