//! Raw EGL + GLES3 bindings (incl. Android extensions) generated by `tools/ndk-bindgen`
//! from the NDK sysroot headers. Regenerate: `just bindgen`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[cfg(target_arch = "arm")]
include!("ffi_arm.rs");
#[cfg(target_arch = "aarch64")]
include!("ffi_aarch64.rs");
#[cfg(target_arch = "x86")]
include!("ffi_i686.rs");
#[cfg(target_arch = "x86_64")]
include!("ffi_x86_64.rs");

#[cfg(target_os = "android")]
#[link(name = "EGL")]
unsafe extern "C" {}

#[cfg(target_os = "android")]
#[link(name = "GLESv3")]
unsafe extern "C" {}
